apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zsb-baclemd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: 
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/environments/development
    repoURL: 'https://github.com/ZSBRybnik/backend'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
